[package]
name = "init-nodejs-project"
version = "0.2.1"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'

[dependencies]
anyhow = "1.0"
chrono = "0.4"
gflags = "0.3"
handlebars = "4.2"
serde = "1.0"
serde_json = "1.0"
