[package]
name = "init-nodejs-project"
version = "0.3.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 's'
strip = true

[dependencies]
chrono = "0.4"
gflags = "0.3"
handlebars = "4.2"
serde_json = "1.0"
