[package]
name = "init-nodejs-project"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'

[dependencies]
anyhow = "1.0.0"
chrono = "0.4.0"
handlebars = "4.2.0"
serde = "1.0.0"
serde_json = "1.0.0"
